#!/usr/bin/env bash
#
# Create .env.local for LOCAL FOUNDER DEVELOPMENT.
#
#   bash scripts/setup-local-env.sh "your founder passphrase here"
#
# Without this, `npm run dev` shows only the sign-in screen: the app returns
# null from founderAuthConfigFromEnv() unless NEHEMIAH_FOUNDER_PASSWORD_HASH
# and NEHEMIAH_SESSION_SECRET are both set, so the login route answers 503 and
# the living interface is never reached.
#
# Writes: .env.local (gitignored — credentials never leave this machine).
# Enables Phase 0 voice output against the local Voicebox by default.
#
# NOT FOR PRODUCTION. Production secrets belong in the deployment platform's
# encrypted secret store, per docs/production/.

set -uo pipefail

PASSPHRASE="${1:-}"
ENV_FILE=".env.local"
VOICEBOX_URL="${VOICEBOX_URL:-http://127.0.0.1:17493}"
VOICEBOX_PROFILE_ID="${VOICEBOX_PROFILE_ID:-6164b83a-c830-4ce1-a599-4ba4759cdba6}"
VOICEBOX_PROFILE_VERSION="${VOICEBOX_PROFILE_VERSION:-kokoro:bm_george}"

ok()   { printf '    \033[32m✓\033[0m %s\n' "$1"; }
die()  { printf '\n    \033[31m✗ %s\033[0m\n\n' "$1"; exit 1; }

if [ -z "$PASSPHRASE" ]; then
  die "Usage: bash scripts/setup-local-env.sh \"your founder passphrase\"
     The passphrase must be at least 16 characters."
fi
if [ "${#PASSPHRASE}" -lt 16 ]; then
  die "Passphrase is ${#PASSPHRASE} characters; at least 16 are required."
fi
[ -f package.json ] || die "Run this from the repository root."
[ -d node_modules ] || die "Dependencies missing. Run: npm ci"

printf '\n\033[1m==> Generating Founder credentials\033[0m\n'
HASH="$(npx tsx scripts/hash-founder-password.ts "$PASSPHRASE")" \
  || die "password hashing failed"
case "$HASH" in
  scrypt\$*) ok "password hash generated (scrypt)" ;;
  *) die "unexpected hash output: $HASH" ;;
esac

SECRET="$(node -e 'console.log(require("crypto").randomBytes(48).toString("base64url"))')" \
  || die "session secret generation failed"
ok "session secret generated (48 random bytes)"

if [ -f "$ENV_FILE" ]; then
  BACKUP="$ENV_FILE.backup.$(date +%s)"
  cp "$ENV_FILE" "$BACKUP"
  ok "existing $ENV_FILE backed up to $BACKUP"
fi

cat > "$ENV_FILE" <<EOF
# Local Founder development. Generated by scripts/setup-local-env.sh.
# Gitignored. NOT production configuration.

NEHEMIAH_FOUNDER_ID=primary-founder
NEHEMIAH_FOUNDER_PASSWORD_HASH=$HASH
NEHEMIAH_SESSION_SECRET=$SECRET
NEHEMIAH_SESSION_TTL_SECONDS=43200
NEHEMIAH_AUTH_VERSION=1

# Phase 0 voice output — Founder-machine-local Voicebox.
# Start it first: bash scripts/voicebox-setup.sh
NEXT_PUBLIC_VOICEBOX_ENABLED=true
NEXT_PUBLIC_VOICEBOX_URL=$VOICEBOX_URL
NEXT_PUBLIC_VOICEBOX_PROFILE_ID=$VOICEBOX_PROFILE_ID
NEXT_PUBLIC_VOICEBOX_PROFILE_VERSION=$VOICEBOX_PROFILE_VERSION
EOF
chmod 600 "$ENV_FILE"
ok "$ENV_FILE written (permissions 600)"

printf '\n\033[1m==> Ready\033[0m\n'
cat <<EOF

  Start the app :  npm run dev
  Open          :  http://localhost:3000
  Sign in with  :  the passphrase you just provided

  Voice is ENABLED against $VOICEBOX_URL
  (profile $VOICEBOX_PROFILE_ID)

  If Voicebox is not running, the app still works — voice degrades silently.
  Start it with: bash scripts/voicebox-setup.sh

EOF
